## Exploracion inicial de produccion no convencional

In [12]:
from pathlib import Path
import pandas as pd

#Permite ejecutar desde la raiz del proyecto o desde noteboooks/.
raiz = Path.cwd()
if raiz.name == "notebooks":
    raiz = raiz.parent

ruta_csv = raiz / "data" / "raw" / "produccion-no-convencional.csv"

print("Archivo encontrado:", ruta_csv.is_file())

Archivo encontrado: True

In [14]:
df_produccion_vaca_muerta = pd.read_csv(
    ruta_csv, 
    encoding="utf-8-sig",
    low_memory=False
)

print(f"Filas: {df_produccion_vaca_muerta.shape[0]:,}")
print(f"Columnas: {df_produccion_vaca_muerta.shape[1]:,}")
display(df_produccion_vaca_muerta.head())

Filas: 421,046
Columnas: 40

,idempresa,anio,mes,idpozo,prod_pet,prod_gas,prod_agua,iny_agua,iny_gas,iny_co2,...,cuenca,provincia,coordenadax,coordenaday,tipo_de_recurso,proyecto,clasificacion,subclasificacion,sub_tipo_recurso,fecha_data
0,YSUR,2015,1,132909,16.74,241.220,13.42,0.0,0.0,0.0,...,NEUQUINA,Neuquén,-69.202207,-39.081820,NO CONVENCIONAL,GAS PLUS,EXPLOTACION,DESARROLLO,TIGHT,2015-01-31
1,YSUR,2018,1,132488,0.00,171.937,0.00,0.0,0.0,0.0,...,NEUQUINA,Rio Negro,-67.864960,-39.016722,NO CONVENCIONAL,GAS PLUS,EXPLOTACION,DESARROLLO,TIGHT,2018-01-31
2,YSUR,2017,1,134325,22.34,365.610,1.20,0.0,0.0,0.0,...,NEUQUINA,Rio Negro,-67.849735,-39.020644,NO CONVENCIONAL,GAS PLUS,EXPLOTACION,DESARROLLO,TIGHT,2017-01-31
3,YSUR,2018,1,132487,0.00,514.696,17.00,0.0,0.0,0.0,...,NEUQUINA,Rio Negro,-67.837875,-39.019313,NO CONVENCIONAL,Sin Proyecto,EXPLOTACION,DESARROLLO,TIGHT,2018-01-31
4,YSUR,2016,1,153522,234.87,1651.240,94.12,0.0,0.0,0.0,...,NEUQUINA,Rio Negro,-67.810843,-39.024083,NO CONVENCIONAL,GAS PLUS,EXPLOTACION,DESARROLLO,TIGHT,2016-01-31

In [16]:
df_produccion_vaca_muerta.info()

<class 'pandas.DataFrame'>
RangeIndex: 421046 entries, 0 to 421045
Data columns (total 40 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   idempresa               421046 non-null  str
 1   anio                    421046 non-null  int64
 2   mes                     421046 non-null  int64
 3   idpozo                  421046 non-null  int64
 4   prod_pet                421046 non-null  float64
 5   prod_gas                421046 non-null  float64
 6   prod_agua               421046 non-null  float64
 7   iny_agua                421046 non-null  float64
 8   iny_gas                 421046 non-null  float64
 9   iny_co2                 421046 non-null  float64
 10  iny_otro                421046 non-null  float64
 11  tef                     421046 non-null  float64
 12  vida_util               8964 non-null    float64
 13  tipoextraccion          420432 non-null  str
 14  tipoestado              420432 non-null  str
 15  tipopozo                420432 non-null  str
 16  observaciones           24001 non-null   str
 17  fechaingreso            421046 non-null  str
 18  rectificado             421046 non-null  str
 19  habilitado              421046 non-null  str
 20  idusuario               421046 non-null  int64
 21  empresa                 421046 non-null  str
 22  sigla                   421046 non-null  str
 23  formprod                421046 non-null  str
 24  profundidad             421046 non-null  float64
 25  formacion               421046 non-null  str
 26  idareapermisoconcesion  421046 non-null  str
 27  areapermisoconcesion    421046 non-null  str
 28  idareayacimiento        421046 non-null  str
 29  areayacimiento          421046 non-null  str
 30  cuenca                  421046 non-null  str
 31  provincia               421046 non-null  str
 32  coordenadax             421046 non-null  float64
 33  coordenaday             421046 non-null  float64
 34  tipo_de_recurso         421046 non-null  str
 35  proyecto                421046 non-null  str
 36  clasificacion           420124 non-null  str
 37  subclasificacion        420124 non-null  str
 38  sub_tipo_recurso        420594 non-null  str
 39  fecha_data              421046 non-null  str
dtypes: float64(12), int64(4), str(24)
memory usage: 225.6 MB

In [ ]:
#Identificando el periodo disponible
fechas = pd.to_datetime(
    {
        "year": df_produccion_vaca_muerta["anio"],
        "month": df_produccion_vaca_muerta["mes"],
        "day": 1
    },
    errors="coerce"
)

print("Primer mes:", fechas.min())
print("Ultimo mes:", fechas.max())
print("Registros con fecha invalida:", fechas.isna().sum())
print("Identificadores pozo-formacion:", df_produccion_vaca_muerta["idpozo"].nunique())

Primer mes: 2006-01-01 00:00:00
Ultimo mes: 2026-07-01 00:00:00
Registros con fecha invalida: 0
Identificadores pozo-formacion: 5089

In [18]:
#Explorar que contiene la base

for columna in ["empresa", "formacion", "tipopozo"]:
    print(f"\nRegistros por {columna}:")
    display(
        df_produccion_vaca_muerta[columna]
        .value_counts(dropna=False)
        .rename_axis(columna)
        .reset_index(name="registros")
    )

Registros por empresa:

                                              empresa  registros
0                                            YPF S.A.     228649
1                                          CAPEX S.A.      21236
2                                     PLUSPETROL S.A.      20750
3                              PAN AMERICAN ENERGY SL      20079
4               COMPAÑÍA GENERAL DE COMBUSTIBLES S.A.      15889
5                                  TOTAL AUSTRAL S.A.      15698
6                                      TECPETROL S.A.      15597
7                                  PAMPA ENERGIA S.A.      13436
8                                SHELL ARGENTINA S.A.       9063
9                          VISTA ENERGY ARGENTINA SAU       8125
10                      YSUR ENERGÍA ARGENTINA S.R.L.       7721
11                           PETROBRAS ARGENTINA S.A.       6595
12                    APACHE ENERGIA ARGENTINA S.R.L.       6448
13       PAN AMERICAN ENERGY (SUCURSAL ARGENTINA) LLC       4827
14                              OILSTONE ENERGIA S.A.       4363
15                      QUINTANA E&P ARGENTINA S.R.L.       3554
16            EXXONMOBIL EXPLORATION ARGENTINA S.R.L.       2578
17                           CHEVRON ARGENTINA S.R.L.       2099
18                           PETROLERA EL TREBOL S.A.       1690
19                                      FLXS OGE S.A        1572
20                                        KILWER S.A.       1457
21                      VISTA OIL & GAS ARGENTINA SAU       1228
22                         PETROLERA ENTRE LOMAS S.A.        911
23                          O&G DEVELOPMENTS LTD S.A.        896
24                  PLUSPETROL CUENCA NEUQUINA S.R.L.        838
25                                 BENTIA ENERGY S.A.        812
26               PETROQUIMICA COMODORO RIVADAVIA S.A.        748
27                           PRESIDENT PETROLEUM S.A.        535
28                           WINTERSHALL ENERGIA S.A.        412
29                      WINTERSHALL DEA ARGENTINA S.A        392
30                      PHOENIX GLOBAL RESOURCES S.A.        299
31                                     ENERGICON S.A.        270
32                        VACA MUERTA INVERSIONES SAU        256
33                   Petrolera Aconcagua Energia S.A.        256
34                                    CGC ENERGIA SAU        243
35                   AMERICAS PETROGAS ARGENTINA S.A.        233
36                                      MEDANITO S.A.        219
37                               ARGENTA ENERGIA S.A.        142
38                       Vista Oil & Gas Argentina SA        140
39                                          ROCH S.A.        114
40                              PATAGONIA ENERGY S.A.         92
41                             GEOPARK ARGENTINA S.A.         90
42                     MADALENA ENERGY ARGENTINA SRL          81
43                    GAS Y PETROLEO DEL NEUQUEN S.A.         79
44                              GRECOIL y CIA. S.R.L.         59
45        GEOPARK ARGENTINA LTD. (SUCURSAL ARGENTINA)         45
46                        TANGO ENERGY ARGENTINA S.A.         36
47                                        VENOIL S.A.         31
48                              MADALENA AUSTRAL S.A.         31
49  APCO OIL AND GAS INTERNATIONAL INC (SUCURSAL A...         28
50               CONTINENTAL RESOURCES ARGENTINA SAU.         24
51                              G Y G OIL SERVICE SRL         23
52                        PECOM SERVICIOS ENERGIA SAU         21
53                            CAPETROL ARGENTINA S.A.         20
54                           CROWN POINT ENERGIA S.A.         16

Registros por formacion:

                 formacion  registros
0              vaca muerta     216445
1                    lajas      77407
2               mulichinco      34749
3               los molles      28011
4               magallanes      15605
5                  precuyo      14603
6                 quintuco      10958
7             punta rosada       9577
8                    agrio       5671
9                basamento       2172
10                  lotena       1595
11  formación improductiva        711
12                tordillo        517
13         sierras blancas        466
14                 chachao        407
15              centenario        404
16              pozo d-129        385
17                   ANITA        209
18            palermo aike        206
19                  rayoso        187
20               yacoraite        185
21              springhill        159
22            grupo chubut        151
23            loma montosa        126
24          mina el carmen         38
25            cañadon seco         32
26           grupo neuquén         31
27            bajo barreal         21
28                tobífera         18

Registros por tipopozo:

            tipopozo  registros
0           Gasífero     228004
1        Petrolífero     163322
2          Otro tipo      28287
3           Sumidero        712
4                NaN        614
5  Inyección de Agua         56
6   Inyección de Gas         50
7           Acuífero          1